### ISSUE TITLE
Folders not opening after running pimpmykali

### ISSUE THREAD

**Issue by niksud** [Dewalt-arch/pimpmykali#16]
I ran the command as given in pimpmykali & got success message. Post restart, upon clicking folders, nothing happens. The folder just does not open up . I have reseted the Kali from snapshot of VirtualBox now

Using below Config:-

VirtualBox 6.1.26
Kali 2020.4

**Comment by Dewalt-arch** [comment]
Issue closed - non-descriptive / non-specific issue, not enough information provided.
