### ISSUE TITLE
Network Connections Not Working in GUI

### ISSUE THREAD

**Issue by merlinsmum** [Dewalt-arch/pimpmykali#2]
I’m fairly inexperienced in this but I have been able to set the network settings via the command line but the interface says there are no active connections and I can’t seem to get changes implemented through the interface to stick. I don’t know if it has anything to do with the script but wanted to see if there’s a fix known? The VM may be used in school.

**Comment by Dewalt-arch** [comment]
Not a Pimpmykali related issue
-- closed --
