### ISSUE TITLE
Unable to install packages for Python3.9-venv

### ISSUE THREAD

**Issue by orypersec** [Dewalt-arch/pimpmykali#22]
I am unable to install packages for Python3.9. I get the following error message: "E: Unable to locate package python3.9-venv".

**Comment by orypersec** [comment]
This error is occurring for the "A - MAPT Course Setup" option.

**Comment by Dewalt-arch** [comment]
Thank you, I am resolving the issue. 

PMK 1.6.0 Should be available later today with a fixed resolution.
