### ISSUE TITLE
Usage behind HTTP proxy

### ISSUE THREAD

**Issue by igufi** [Dewalt-arch/pimpmykali#25]
I'm trying to use pimpmykali in an environment that forces all http(s) traffic to go via a proxy. I've updated the following configs due to this:
~/etc/apt/apt/apt.conf.d/proxy.conf
~/.gitconfig
~/.curlrc
~/.wgetrc
... and added two env variables: http_proxy and https_proxy

Individually all the above work correctly but for some reason when running pimpmykali for the first time (menu option N) the process gets stuck on pip installation. It looks like curl is not respecting the proxy setting:

![image](https://user-images.githubusercontent.com/1605764/212889840-3ae7565b-82bc-48a1-8f94-92bc3eb0f509.png)

Is there a way to force pimpmykali to respect the system's proxy settings?

**Comment by Dewalt-arch** [comment]
PMK respects whatever networking / proxying you have setup. 
Script does not make / change networking or proxy configurations. 
Closed, non script related issue
