### ISSUE TITLE
Read error at byte 219806326

### ISSUE THREAD

**Issue by TimanLab** [Dewalt-arch/pimpmykali#27]
For first time pimp my kali i pressed N and the process started however the following error cannot be bypassed and keeps looping all over again. 

2023-04-23 11:27:49 (158 KB/s) - Read error at byte 219806326 (The request is invalid.).Retrying.

--2023-04-23 11:27:52--  (try: 4)  https://codeload.github.com/danielmiessler/SecLists/zip/refs/heads/master
Connecting to codeload.github.com (codeload.github.com)|20.87.225.213|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘/tmp/SecList.zip’

**Comment by Dewalt-arch** [comment]
Thank you, I will update the url to the current 2023.1 seclists release in the next 24 hours
