### ISSUE TITLE
Kali Linux Not Detected - WSL/WSL2/Anything else is unsupported

### ISSUE THREAD

**Issue by Yeo8023** [Dewalt-arch/pimpmykali#32]
I try to run the pimpmykali but this error occur 
<img width="458" alt="image" src="https://github.com/Dewalt-arch/pimpmykali/assets/96370502/8ade9d3c-ecc9-4cd9-b580-635ff8fee1c6">
For your information, the Kali Linux os I installed it as an app using wsl. I am not sure whether it is the cause of this issue or not.

**Comment by Dewalt-arch** [comment]
That is correct, Kali Linux under WSL or WSL2 is unsupported by this project.
