### ISSUE TITLE
impacket depedency issue

### ISSUE THREAD

**Issue by peterrakolcza** [Dewalt-arch/pimpmykali#35]
Hey

I am using a M1 Macbook Pro with UTM running the latest Kali Linux
<img width="907" alt="image" src="https://github.com/Dewalt-arch/pimpmykali/assets/6462276/8024b290-c890-4c1e-992c-ced50ff8b9ab">

However, after running the 'N' option I get the following error message:
<img width="1112" alt="image" src="https://github.com/Dewalt-arch/pimpmykali/assets/6462276/9b275be1-51cd-4150-be18-fbdaae411a05">

I have tried rebooting, but no lock. Furthermore, after running the '!' option with should nuke the impacket installation, I can still run impacket-* commands. What is even weirder, that using impacket like this works:
<img width="1099" alt="image" src="https://github.com/Dewalt-arch/pimpmykali/assets/6462276/38e78b8f-bac5-4ace-9533-cade6b91d46a">

Any help is appreciated!

**Comment by Dewalt-arch** [comment]
Impacket 0.9.19 will not run on Apple Silicon, M1, M2, M3 (ntlmrelayx.py) 

Use a newer version of impacket 0.10.x or newer (impacket-ntlmrelayx.py)
