### ISSUE TITLE
Updates to /etc/apt/source.list don't follow Kali's new url addition

### ISSUE THREAD

**Issue by DevinCarpenter** [Dewalt-arch/pimpmykali#36]
The latest version of pimpmykali is not picking up the new changes from kali that the firmware component has changed from 'non-free' to 'non-free-firmware'

It was able to detect the lowest ping mirror but the mirror does not work due to the new kali change.

I've reverted back to using the kali recommended source in /etc/apt/sources.list:
 `deb http://http.kali.org/kali kali-rolling main contrib non-free non-free-firmware`

Now all package installs and updates are received correctly.

Here's the error I got after running the pimpmykali sources update:

```  Could not connect to mirror.vinehost.net:80 (127.172.0.1). - connect (111: Connection refused)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://mirror.vinehost.net/kali/dists/kali-rolling/InRelease  Could not connect to mirror.vinehost.net:80 (127.172.0.1). - connect (111: Connection refused)
W: Some index files failed to download. They have been ignored, or old ones used instead.
N: Repository 'Kali Linux' changed its 'firmware component' value from 'non-free' to 'non-free-firmware'
N: More information about this can be found online at: https://www.kali.org/blog/non-free-firmware-transition/
```

**Comment by Dewalt-arch** [comment]
Revision 1.7.9a3

added sed -i /etc/apt/sources.list, (aprox line 1089) statement in fix_sources function to correct non-free to "non-free non-free-firmware" in /etc/apt/source.list
deb and deb-src lines

Thank you.
