### ISSUE TITLE
Suggestion to improve the readme pimpmyreadme

### ISSUE THREAD

**Issue by TheFern2** [Dewalt-arch/pimpmykali#4]
Hey Dewalt, I think the readme could use some pimping itself. I suggest moving all the rev changes to a file called changelog.txt, or just changelog. This brings up the menu choices right to the top, so anyone can see what it does instead of the long scroll to the bottom.

Could also add a picture of the menu as well. Let me know if you like these ideas, I can submit a PR.

**Comment by Dewalt-arch** [comment]
Agreed, Ill see about cleaning things up / moving things around, etc.
