### ISSUE TITLE
Cant install pimpmykali 

### ISSUE THREAD

**Issue by HelpMe518** [Dewalt-arch/pimpmykali#42]
This is my message when trying to install - might be to do with not running in a virtual machine im not sure 

[!!] Kali Linux Not Detected - WSL/WSL2/Anything else is unsupported [!!]

**Comment by Dewalt-arch** [comment]
Pimpmykali.sh checks if the distro is kali linux using 2 methods, uname - a and cat /etc/os-release 
Lines 105 - 119 check_distro function and that function is called via line 2494. 

I have downloaded Kali Linux 2024.2, ran pimpmykali.sh against 2024.2 and see no issues

If you are running Kali as your hostOS pimpmykali will still run, although if you are attempting to use WSL/WSL2 or run pimpmykali.sh on a disto that is not Kali Linux, pimpmykali.sh will not run and will exit with the error message
[!!] Kali Linux Not Detected - WSL/WSL2/Anything else is unsupported [!!]
