### ISSUE TITLE
No Mount for binfmt misc

### ISSUE THREAD

**Issue by Reuvi** [Dewalt-arch/pimpmykali#45]
the binfmt misc is properly setup with all the translators but because it is not mounted by default on Kali it will not work until you manually run "sudo mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc". Fix: add this functionality to the setup script.

**Comment by Dewalt-arch** [comment]
It will be added to the next release of Pimpmykali

Thank you for the suggestion, closing issue.
