### ISSUE TITLE
Usernane not detected

### ISSUE THREAD

**Issue by gru3zi** [Dewalt-arch/pimpmykali#48]
On a fresh install of Kali 2024.4 there seems to be a number of errors

![2024-12-29_11-14](https://github.com/user-attachments/assets/8ea95259-9636-4740-aebf-91234c2c7464)
![image](https://github.com/user-attachments/assets/b53a7831-c749-4f08-b538-d40cf291b5f1)

**Comment by Dewalt-arch** [comment]
Thank you for the report, the issue is being investigated with Kali Linux 2024.4

**Comment by Dewalt-arch** [comment]
I am unable to reproduce the error using a new Kali Linux 2024.4 vm in Virtualbox, Vmware or UTM/Qemu, with the default user 'kali'

Please provide additional information regarding your Kali Linux setup

Where is kali installed in a Hypervisor or on Bare Metal?
Default user kali or custom username?
Login Manager? LightDM? SDDM? GDM? etc
Desktop Environment/Window Manager? (XFCE, Gnome, KDE, i3/i3-Gaps, AwesomeWM, etc)
