### ISSUE TITLE
About download speed

### ISSUE THREAD

**Issue by SAGEof6iixPATHS** [Dewalt-arch/pimpmykali#7]
Helllo!

Can you add a section to increase the download speed of apt and all...
I have 5-6 mbps download speed but the apt is catching 30kbps...

Thank you!

**Comment by Dewalt-arch** [comment]
There are other scripts out there ( Mirrorscript-v2 being one of them  _https://github.com/IceM4nn/mirrorscript-v2_ ) 
that already find the fastest mirror for you in kali linux. 

The only change PMK makes to /etc/apt/sources.list is the enabling of the 
deb-sec repo. 

Currently there are no plans to implement such a feature in pimpmykali
at this time.

**Comment by Dewalt-arch** [comment]
Please see pimpmykali v1.3.2 - Pimpmykali now with mirrors!!
